---
  title: Gonzalo Gutierrez
  description: Software Engineer
  language: en
  repository: https://github.com/Gonzalogdlr/My-Page
  email: gonzaloggdlr@gmail.com
  social:
    # twitter: 
    github: Gonzalogdlr
    linkedin: gonzalo-ggdlr
  analytics: 
  navigation:
  incremental: false

  